### ISSUE TITLE
“Pick a Date/Time” option appearing inconsistently

### ISSUE THREAD

**Issue by ckprice** [bwinton/SnoozeTabs#179]
Reported by Sharon, we'll add a video to this issue.

**Comment by sharonbautista** [comment]
Watch [this clip until the end](http://www.usertesting.com/videos/8wFVFcN5x2YnnYO8ee4giQ/clips/2?note_id=clip-1147923&shared=ye0xSCgJ) (<1 min), and you can see how "Pick a Date/Time" appears and then is cut-off and no longer visible above "Manage Snoozed Tabs."

[This is the moment](http://www.usertesting.com/videos/8wFVFcN5x2YnnYO8ee4giQ/clips/3?note_id=clip-1147936&shared=KaBlVdwW) (<15 seconds) when the participant realized that "Pick a Date/Time" is appearing and then disappearing.

**Comment by bwinton** [comment]
Right, so it's getting pushed off the end, because we're using the narrow window, which I _think_ we've fixed…  It would be good to see if we can replicate this with a newer version of the add-on.

**Comment by lmorchard** [comment]
Ah, yeah, [I think this was an issue on Windows that I fixed](https://github.com/bwinton/SnoozeTabs/commit/808f18dde48ff1b456e8fc2287cbd4fc8147618d) but that might not have made it into the build in testing. Going to close this, but we can re-open if it resurfaces.

**Comment by SoftVision-EmilPasca** [comment]
This still happens on the latest Firefox release (51.0.1), but I haven't manage to reproduce it on the latest Nightly (54.0a1), because of this I've decided to find a regression range and found out that this is a Firefox issue and it was fixed by the following bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1287209

**Comment by ckprice** [comment]
Let's make it work well for toolbar, then make it scroll in the hamburger menu instead of adapting styles.

**Comment by wresuolc** [comment]
This is a hard problem with some inconsistencies.  It's hard to reproduce, but when it happens it breaks everything.  If we focus a fix on the toolbar case it breaks the menubar case and vice versa.

We'll focus on fixing the toolbar case in this issue, with the understanding that the menubar will suffer.
